sync:
  - source: graphgen/
    dest: graphgen/
  - source: resources/nltk_data/
    dest: resources/nltk_data/
  - source: resources/examples/
    dest: resources/examples/
  - source: resources/images/
    dest: resources/images/
  - source: webui/
    dest: webui/
  - source: webui/app.py
    dest: app.py
  - source: requirements.txt
    dest: requirements.txt
  - source: README_HF.md
    dest: README.md
  - source: LICENSE
    dest: LICENSE
