read:
  input_file: /workspace/hayrapetyan/get_cfa_book/test_cfa_book_cut.jsonl # input file path, support json, jsonl, txt, csv. See resources/input_examples for examples
split:
  chunk_size: 1024 # chunk size for text splitting
  chunk_overlap: 100 # chunk overlap for text splitting
search: # web search configuration
  enabled: false # whether to enable web search
quiz_and_judge: # quiz and test whether the LLM masters the knowledge points
  enabled: false
partition: # atomic applies to each node description, to each edge (no partitioning, actually)
  method: ece  # not used in atomic!
  method_params:  {}
generate:
  mode: atomic 
  data_format: Alpaca # Alpaca, Sharegpt, ChatML
