input_data_type: raw
input_file: resources/input_examples/raw_demo.jsonl
output_data_type: cot
tokenizer: cl100k_base
search:
  enabled: false
  search_types: []
method_params:
  method: leiden
  max_size: 20 # Maximum size of communities
  use_lcc: false
  random_seed: 42
